### ISSUE TITLE
Insufficient vertical space after last list item

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#41]
The gap after the last item of an ordered list or unordered list is too small and so the following text is too close. Screenshots of editing and display view attached.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5347540/79576282-06bec400-8091-11ea-9b93-13546e140082.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/5347540/79576205-eabb2280-8090-11ea-81ba-637441edb1a5.png">

**Comment by ghwood** [comment]
Related (or maybe included in https://github.com/ietf-tools/wagtail_website/issues/15

**Comment by JayDaley** [comment]
It looks to me as if there is insufficient space below all list items, making them hard to read, particularly with the large line height.  Adding padding to the bottom should help:
```css
.rich-text ul li, .standard-list li {
list-style: none;
position: relative;
padding-left: 20px;
padding-bottom: 1em;    /* Added */
}
```
