### ISSUE TITLE
Excessive whitespace around tables

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#75]
For some unknown reason, tables have an additional 50px right margin and top margin set by:
```css
@media (min-width: 620px)
.block-table {
margin: 50px 0;
border: 0;
overflow: auto;
width: calc(100% - 50px);
```
and
```css
.block-table>table {
width: calc(100% - 50px);
overflow: auto;
}
```
If there is a table caption then this is added rather than sitting in the margin space, so there is no issue if the top margin is remove.

Both margins can go entirely.

**Comment by JayDaley** [comment]
For very wide tables this will take them right up to the edge of the body, which may be acceptable, but if not then
```css
max-width: 902px; 
```
Can be added to .block-table.

**Comment by JayDaley** [comment]
I've reviewed this following the template refactoring and it is now just

``` css
@media (min-width: 576px)
.block-table {
margin: 50px 0;
border: 0;
width: calc(100% - 50px);
}
```

the margin and width attributes can be deleted.
