### ISSUE TITLE
Excessive whitespace above and below body text

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#77]
The body text has excessive whitespace above and below it, set by:
```css
.body, .body-visable, .body-no-space {
position: relative;
padding-top: 2em;        /* suggest this is reduced to 1em */
padding-bottom: 2em;        /* suggest this is reduced to 1em */
}
```
However there are some nasty kludges elsewhere that also need to be changed.  For example:
```css
.faq:before {
content: '';
display: block;
background: #F3F5F6;
position: absolute;
top: -6.1em;        /* needs to be reduced to -5.1em if changes made above */
left: -30em;
height: calc(100% + 8.1em);    /* needs to be +7.1em if changes made above */
width: calc(100% + 30em);
}
```
There may be more.
