### ISSUE TITLE
Excessive whitespace in footer

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#78]
The footer has excessive whitespace set by:
```css
footer {
padding: 3em 0;
background: #49555c;
display: block;
clear: both;
}
```
The 3em should be reduced to 1em, which is more readable.
