### ISSUE TITLE
Breadcrumbs so large that they distracts from heading below

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#79]
The breadcrumbs are so large that they distract from the heading below.  The size is set by:
```css
.breadcrumb li {
font-size: 18px;        /* reduce to 14px */
}
```
With the font size reduced to 14px the spacing also needs to be adjusted by changing:
```css
.breadcrumb {
padding-top: 1.5em;        /* reduce to 0em */
}
```
