### ISSUE TITLE
Excessive whitespace due to max-width: 720px for multiple elements

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/wagtail_website#82]
This CSS sets a max-width of 720px for multiple elements and so leaves a huge whitespace gap on the right of the body text:
```css
h1, h2, .body .block-heading, .body-visable .block-heading, .body-no-space .block-heading, h3, h4, h5, p, ol {
max-width: 720px;
-webkit-transition: all 0.25s ease 0s;
-moz-transition: all 0.25s ease 0s;
-ms-transition: all 0.25s ease 0s;
-o-transition: all 0.25s ease 0s;
transition: all 0.25s ease 0s;
}
```
A max-width of 902px still leaves a 50px right margin, which is ample.
